creation_rules:
  - path_regexp: .*secrets\.yaml$
    key_groups:
      - age:
        - age1ej7nqnzhkvm5f7t9my5dprv9236t6dge5kzr5qj6xsgl34x8gegsmj6jlx
        - age1vxek767gxu5mj27acgfpr7w0zdx595crecwdjuwsrf5w80q43crstz29sl
