#!/usr/bin/env lua
-- modules/overlays/email/backend/HimalayaEngine.lua
-- Dedicated backend engine for Himalaya CLI integration in Quickshell

local action = arg[1] or ""
local home_dir = os.getenv("HOME") or "/tmp"
local runtime_dir = os.getenv("XDG_RUNTIME_DIR") or "/tmp"
local cache_dir = home_dir .. "/.cache/himalaya"
local cache_file = cache_dir .. "/emails.json"
local config_dir = home_dir .. "/.config/himalaya"
local config_file = config_dir .. "/config.toml"

local path_prefix = 'export PATH="$HOME/.nix-profile/bin:/etc/profiles/per-user/${USER:-$(id -un 2>/dev/null)}/bin:/run/current-system/sw/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin:$PATH"; '

local function run_cmd(cmd)
    local pipe = io.popen(path_prefix .. cmd)
    if not pipe then return "" end
    local output = pipe:read("*a") or ""
    pipe:close()
    return output
end

local function escape_json(s)
    if not s then return '""' end
    local escapes = {
        ['\\'] = '\\\\',
        ['"']  = '\\"',
        ['\b'] = '\\b',
        ['\f'] = '\\f',
        ['\n'] = '\\n',
        ['\r'] = '\\r',
        ['\t'] = '\\t'
    }
    return '"' .. s:gsub('[%z\1-\31\\"]', function(c)
        return escapes[c] or string.format('\\u%04x', c:byte())
    end) .. '"'
end

-- ============================================================================
-- 1. SETUP WIZARD DEPLOYMENT (Invoked with 7 arguments from HimalayaSetupModal)
-- ============================================================================
if #arg >= 7 and not action:match("^[A-Z_]+$") and action ~= "sync" then
    local email     = arg[1]
    local name      = arg[2]
    local password  = arg[3]
    local imap_host = arg[4]
    local imap_port = tonumber(arg[5]) or 993
    local smtp_host = arg[6]
    local smtp_port = tonumber(arg[7]) or 465

    local imap_enc = (imap_port == 993) and "tls" or "start-tls"
    local smtp_enc = (smtp_port == 465) and "tls" or "start-tls"

    os.execute(string.format('mkdir -p %q %q', config_dir, cache_dir))

    local toml_content = string.format([[# Himalaya configuration generated by Quickshell
[accounts.default]
default = true
email = %q
display-name = %q
downloads-dir = "~/Downloads"

backend.type = "imap"
backend.host = %q
backend.port = %d
backend.encryption.type = %q
backend.login = %q
backend.auth.type = "password"
backend.auth.raw = %q

message.send.backend.type = "smtp"
message.send.backend.host = %q
message.send.backend.port = %d
message.send.backend.encryption.type = %q
message.send.backend.login = %q
message.send.backend.auth.type = "password"
message.send.backend.auth.raw = %q
]], email, name, imap_host, imap_port, imap_enc, email, password,
    smtp_host, smtp_port, smtp_enc, email, password)

    local f = io.open(config_file, "w")
    if f then
        f:write(toml_content)
        f:close()
        os.execute(string.format('chmod 600 %q', config_file))
        os.execute(path_prefix .. 'himalaya envelope list -s 30 --output json >/dev/null 2>&1 &')
        os.exit(0)
    else
        os.exit(1)
    end
end

-- ============================================================================
-- 2. SYNC / ENVELOPE LISTING
-- ============================================================================
if action == "sync" or action == "" then
    os.execute(string.format('mkdir -p %q', cache_dir))

    local cached_bodies = {}
    local existing_f = io.open(cache_file, "r")
    if existing_f then
        local raw = existing_f:read("*a")
        existing_f:close()
        if raw then
            for id_str, body in raw:gmatch('"id"%s*:%s*"?([^",%s]+)"?.-"body_content"%s*:%s*"([^"]+)"') do
                cached_bodies[id_str] = body
            end
        end
    end

    local json_out = run_cmd("himalaya envelope list --folder INBOX -s 100 --output json 2>/dev/null || himalaya envelope list -s 100 --json 2>/dev/null")
    if not json_out or #json_out:gsub("%s+", "") == 0 then
        return
    end

    local entries = {}
    for block in json_out:gmatch("%b{}") do
        local id = block:match('"id"%s*:%s*"?([^",%s]+)"?')
        local subject = block:match('"subject"%s*:%s*"([^"]*)"') or "(No Subject)"
        local date = block:match('"date"%s*:%s*"([^"]*)"') or ""

        local from_name = block:match('"from"%s*:%s*{[^}]*"name"%s*:%s*"([^"]*)"')
        local from_addr = block:match('"from"%s*:%s*{[^}]*"addr"%s*:%s*"([^"]*)"')

        if not from_addr then
            local raw_from = block:match('"from"%s*:%s*"([^"]*)"')
            if raw_from then
                from_addr = raw_from:match("<([^>]+)>") or raw_from
                from_name = raw_from:match("^([^<]+)")
            end
        end

        local flags_tbl = {}
        local flags_raw = block:match('"flags"%s*:%s*%[([^%]]*)%]')
        if flags_raw then
            for flag in flags_raw:gmatch('"([^"]+)"') do
                table.insert(flags_tbl, '"' .. flag:lower() .. '"')
            end
        end
        if #flags_tbl == 0 then
            table.insert(flags_tbl, '"unseen"')
        end

        local has_att = block:match('"has_attachment"%s*:%s*true') ~= nil

        if id then
            local cached_body = cached_bodies[id] or ""
            local entry_json = string.format(
                '{"id":%q,"folder":"inbox","subject":%s,"date":%s,"from":{"name":%s,"addr":%s},"flags":[%s],"has-attachment":%s,"body_content":%s}',
                id,
                escape_json(subject),
                escape_json(date),
                escape_json(from_name or from_addr or "Unknown"),
                escape_json(from_addr or ""),
                table.concat(flags_tbl, ","),
                has_att and "true" or "false",
                escape_json(cached_body)
            )
            table.insert(entries, entry_json)
        end
    end

    if #entries > 0 then
        local tmp_file = cache_file .. ".tmp." .. os.time()
        local wf = io.open(tmp_file, "w")
        if wf then
            wf:write("[\n" .. table.concat(entries, ",\n") .. "\n]\n")
            wf:close()
            os.execute(string.format('mv -f %q %q', tmp_file, cache_file))
        end
    end

-- ============================================================================
-- 3. FETCH MESSAGE BODY
-- ============================================================================
elseif action == "FETCH_BODY" or action == "fetch-body" then
    local msg_id = arg[2]
    local folder = arg[3] or "INBOX"
    if not msg_id then return end

    local cmd = string.format('himalaya message read --folder %q %q 2>/dev/null || himalaya message read %q 2>/dev/null', folder, msg_id, msg_id)
    local body = run_cmd(cmd)
    if not body or #body == 0 then
        body = "Message body could not be fetched from server."
    end

    local out_payload = msg_id .. "\n" .. body
    local out_path = runtime_dir .. "/qmail_active_body.txt"

    local f = io.open(out_path, "w")
    if f then
        f:write(out_payload)
        f:close()
    end

    local fallback_f = io.open("/tmp/qmail_active_body.txt", "w")
    if fallback_f then
        fallback_f:write(out_payload)
        fallback_f:close()
    end

-- ============================================================================
-- 4. OUTBOUND DELIVERY (SEND)
-- ============================================================================
elseif action == "SEND" or action == "send" then
    local to = arg[2]
    local subject = arg[3]
    local body = arg[4] or ""

    if not to or to == "" then return end

    local email_raw = string.format("To: %s\nSubject: %s\n\n%s", to, subject, body)
    local tmp_msg = string.format("%s/qmail_send_%d.eml", runtime_dir, os.time())
    local mf = io.open(tmp_msg, "w")
    if mf then
        mf:write(email_raw)
        mf:close()
        local send_cmd = string.format('himalaya template send < %q 2>/dev/null || himalaya message write -H "To:%s" -H "Subject:%s" %q 2>/dev/null', tmp_msg, to, subject, body)
        local res = os.execute(path_prefix .. send_cmd)
        os.remove(tmp_msg)
        if res == 0 or res == true then
            os.execute(string.format('notify-send -a Himalaya "Email Sent" "Delivered to %s"', to))
        end
    end

-- ============================================================================
-- 5. FLAGS & MAILBOX ACTIONS
-- ============================================================================
elseif action == "DELETE" or action == "delete" then
    local msg_id = arg[2]
    local folder = arg[3] or "INBOX"
    if msg_id then
        os.execute(path_prefix .. string.format('himalaya message delete --folder %q %q 2>/dev/null || himalaya message delete %q 2>/dev/null', folder, msg_id, msg_id))
    end

elseif action == "STAR" then
    local msg_id = arg[2]
    local folder = arg[3] or "INBOX"
    if msg_id then
        os.execute(path_prefix .. string.format('himalaya flag add --folder %q %q flagged 2>/dev/null || himalaya flag add %q flagged 2>/dev/null', folder, msg_id, msg_id))
    end

elseif action == "UNSTAR" then
    local msg_id = arg[2]
    local folder = arg[3] or "INBOX"
    if msg_id then
        os.execute(path_prefix .. string.format('himalaya flag remove --folder %q %q flagged 2>/dev/null || himalaya flag remove %q flagged 2>/dev/null', folder, msg_id, msg_id))
    end

elseif action == "READ" then
    local msg_id = arg[2]
    local folder = arg[3] or "INBOX"
    if msg_id then
        os.execute(path_prefix .. string.format('himalaya flag add --folder %q %q seen 2>/dev/null || himalaya flag add %q seen 2>/dev/null', folder, msg_id, msg_id))
    end

elseif action == "UNREAD" then
    local msg_id = arg[2]
    local folder = arg[3] or "INBOX"
    if msg_id then
        os.execute(path_prefix .. string.format('himalaya flag remove --folder %q %q seen 2>/dev/null || himalaya flag remove %q seen 2>/dev/null', folder, msg_id, msg_id))
    end

elseif action == "MOVE" then
    local msg_id = arg[2]
    local from_folder = arg[3] or "INBOX"
    local to_folder = arg[4] or "Trash"
    if msg_id then
        os.execute(path_prefix .. string.format('himalaya message move --folder %q %q %q 2>/dev/null', from_folder, msg_id, to_folder))
    end

elseif action == "DOWNLOAD_ATTACHMENTS" then
    local msg_id = arg[2]
    local folder = arg[3] or "INBOX"
    local dest_dir = arg[4] or (home_dir .. "/Downloads")
    if msg_id then
        os.execute(string.format('mkdir -p %q', dest_dir))
        os.execute(path_prefix .. string.format('himalaya attachment download --folder %q %q --dir %q 2>/dev/null', folder, msg_id, dest_dir))
        os.execute(string.format('notify-send -a Himalaya "Attachments Downloaded" "Saved to %s"', dest_dir))
    end

elseif action == "CONTACT" then
    local nick = arg[2] or ""
    local email = arg[3] or ""
    if email ~= "" then
        local contacts_file = home_dir .. "/Documents/Contacts"
        os.execute(string.format('mkdir -p %q', home_dir .. "/Documents"))
        local cf = io.open(contacts_file, "a")
        if cf then
            cf:write(string.format("%s <%s>\n", nick ~= "" and nick or email, email))
            cf:close()
            os.execute(string.format('notify-send -a Himalaya "Contact Saved" "%s <%s>"', nick, email))
        end
    end
end
